// Shared state: declared once, read/written by all desktop JS modules.
// Must be loaded first, before any other desktop JS file.

var i18n = {
    en: {
        'sidebarSubtitle': 'Desktop',
        'menu.home': 'Home',
        'menu.settings': 'Settings',
        'menu.back_to_desktop': 'Desktop',
        'menu.exit_app': 'Exit App',
        'menu.running_apps': 'Running Apps',
        'title.desktop': 'Desktop',
        'title.settings': 'Settings',
        'empty.no_apps': 'No Apps Found',
        'empty.no_apps_desc': 'Add apps to the app folder to get started.',
        'settings.general': 'General',
        'settings.language': 'Language',
        'settings.theme': 'Theme',
        'settings.global_hotkey': 'Global Hotkey',
        'settings.hotkey_desc': 'Register a global hotkey to launch Skillup Desktop from anywhere.',
        'settings.hotkey_combination': 'Hotkey Combination',
        'settings.enable_hotkey': 'Enable Global Hotkey',
        'settings.hotkey_enabled': 'Enabled',
        'settings.hotkey_disabled': 'Disabled',
        'settings.desktop_env': 'Desktop Environment:',
        'settings.current_command': 'Current Command:',
        'settings.hotkey_note': 'Note: This feature works on GNOME desktop environment. For KDE/XFCE, please register the hotkey manually in system settings.',
        'settings.account': 'Account',
        'settings.account_photo': 'Photo',
        'settings.account_change_photo': 'Change',
        'settings.account_remove_photo': 'Remove',
        'settings.account_name': 'Name',
        'settings.account_save': 'Save',
        'settings.account_id': 'ID',
        'settings.account_name_saved': 'Saved.',
        'settings.account_remove_photo_confirm_title': 'Remove Photo',
        'settings.account_remove_photo_confirm_text': 'Are you sure you want to remove the profile photo?',
        'settings.about': 'About',
        'settings.build': 'Build',
        'settings.version': 'Version',
        'settings.suggest': 'Feedback',
        'dialog.ok': 'OK',
        'dialog.yes': 'Yes',
        'dialog.no': 'No',
        'app.launch_failed_title': 'Failed to Launch App',
        'app.launch_failed_text': 'The app could not be started.'
    },
    ko: {
        'sidebarSubtitle': '데스크탑',
        'menu.home': '바탕화면',
        'menu.settings': '환경설정',
        'menu.back_to_desktop': '바탕화면',
        'menu.exit_app': '앱 종료',
        'menu.running_apps': '실행 중',
        'title.desktop': '바탕화면',
        'title.settings': '환경설정',
        'empty.no_apps': '앱이 없습니다',
        'empty.no_apps_desc': '시작하려면 앱 폴더에 앱을 추가하세요.',
        'settings.general': '일반',
        'settings.language': '언어',
        'settings.theme': '테마',
        'settings.global_hotkey': '전역 단축키',
        'settings.hotkey_desc': '어디서나 Skillup 데스크탑을 실행할 수 있는 전역 단축키를 등록합니다.',
        'settings.hotkey_combination': '단축키 조합',
        'settings.enable_hotkey': '전역 단축키 활성화',
        'settings.hotkey_enabled': '활성화됨',
        'settings.hotkey_disabled': '비활성화됨',
        'settings.desktop_env': '데스크탑 환경:',
        'settings.current_command': '현재 명령:',
        'settings.hotkey_note': '참고: 이 기능은 GNOME 데스크톱 환경에서 작동합니다. KDE/XFCE의 경우 시스템 설정에서 수동으로 단축키를 등록해주세요.',
        'settings.account': '계정',
        'settings.account_photo': '사진',
        'settings.account_change_photo': '변경',
        'settings.account_remove_photo': '제거',
        'settings.account_name': '이름',
        'settings.account_save': '저장',
        'settings.account_id': '아이디',
        'settings.account_name_saved': '저장이 되었습니다.',
        'settings.account_remove_photo_confirm_title': '사진 제거',
        'settings.account_remove_photo_confirm_text': '프로필 사진을 제거하시겠습니까?',
        'settings.about': '정보',
        'settings.build': '빌드',
        'settings.version': '버전',
        'settings.suggest': '건의하기',
        'dialog.ok': '확인',
        'dialog.yes': '예',
        'dialog.no': '아니오',
        'app.launch_failed_title': '앱 실행 실패',
        'app.launch_failed_text': '앱을 시작할 수 없습니다.'
    }
};

var currentLanguage = 'en';
window.currentLanguage = currentLanguage;
var currentPage = 'home';
var currentApp = null;
var apps = [];
var runningApps = [];
var sidebarCollapsed = false;
