// Shared state: declared once, read/written by all desktop JS modules.
// Must be loaded first, before any other desktop JS file.

var i18n = {
    en: {
        'sidebarSubtitle': 'Desktop',
        'menu.home': 'Home',
        'menu.settings': 'Settings',
        'menu.back_to_desktop': 'Desktop',
        'menu.exit_app': 'Exit App',
        'menu.running_apps': 'Running Apps',
        'title.desktop': 'Desktop',
        'title.settings': 'Settings',
        'empty.no_apps': 'No Apps Found',
        'empty.no_apps_desc': 'Add apps to the app folder to get started.',
        'settings.general': 'General',
        'settings.language': 'Language',
        'settings.theme': 'Theme',
        'settings.global_hotkey': 'Global Hotkey',
        'settings.hotkey_desc': 'Register a global hotkey to launch Skillup Desktop from anywhere.',
        'settings.hotkey_combination': 'Hotkey Combination',
        'settings.enable_hotkey': 'Enable Global Hotkey',
        'settings.hotkey_enabled': 'Enabled',
        'settings.hotkey_disabled': 'Disabled',
        'settings.desktop_env': 'Desktop Environment:',
        'settings.current_command': 'Current Command:',
        'settings.hotkey_note': 'Note: This feature works on GNOME desktop environment. For KDE/XFCE, please register the hotkey manually in system settings.',
        'settings.account': 'Account',
        'settings.account_photo': 'Photo',
        'settings.account_change_photo': 'Change',
        'settings.account_remove_photo': 'Remove',
        'settings.account_name': 'Name',
        'settings.account_save': 'Save',
        'settings.account_id': 'ID',
        'settings.account_name_saved': 'Saved.',
        'settings.account_remove_photo_confirm_title': 'Remove Photo',
        'settings.account_remove_photo_confirm_text': 'Are you sure you want to remove the profile photo?',
        'settings.about': 'About',
        'settings.build': 'Build',
        'settings.version': 'Version',
        'settings.build_date': 'Build Date',
        'settings.suggest': 'Feedback',
        'dialog.ok': 'OK',
        'dialog.yes': 'Yes',
        'dialog.no': 'No',
        'dialog.cancel': 'Cancel',
        'app.launch_failed_title': 'Failed to Launch App',
        'app.launch_failed_text': 'The app could not be started.',
        'app.open_new_window_confirm_title': 'Open in New Window',
        'app.open_new_window_confirm_text': 'The app will be reset and opened in a new window. Continue?',
        'settings.groups': 'Groups',
        'settings.groups_desc': 'Create and manage user groups.',
        'settings.group_new': 'New Group',
        'settings.group_name': 'Group Name',
        'settings.group_name_placeholder': 'Enter group name',
        'settings.group_description': 'Description',
        'settings.group_description_placeholder': 'Short description (optional)',
        'settings.group_all_user': 'Include all users',
        'settings.group_join_policy': 'Join Policy',
        'settings.group_join_policy_free': 'Free (anyone can join)',
        'settings.group_join_policy_approve': 'Approval required',
        'settings.group_join_policy_all_user': 'All Users',
        'settings.group_create': 'Create',
        'settings.group_save': 'Save',
        'settings.group_delete': 'Delete Group',
        'settings.group_delete_confirm_title': 'Delete Group',
        'settings.group_delete_confirm_text': 'Are you sure you want to delete this group? This cannot be undone.',
        'settings.group_members': 'Members',
        'settings.group_add_member': 'Add Member',
        'settings.group_add_member_placeholder': 'Enter ID to add as member',
        'settings.group_leave': 'Leave Group',
        'settings.group_leave_confirm_title': 'Leave Group',
        'settings.group_leave_confirm_text': 'Are you sure you want to leave this group?',
        'settings.group_remove_member': 'Remove',
        'settings.group_grant_admin': 'Grant Admin',
        'settings.group_revoke_admin': 'Revoke Admin',
        'settings.group_admin_badge': 'Admin',
        'settings.group_last_admin_error': 'Cannot remove the last admin. Assign another admin first.',
        'settings.group_join_requests': 'Join Requests',
        'settings.group_approve': 'Approve',
        'settings.group_reject': 'Reject',
        'settings.group_no_requests': 'No pending requests.',
        'settings.group_startup_requests_title': 'Pending Join Requests',
        'settings.group_startup_requests_text': 'The following users are waiting to join your groups:',
        'settings.group_startup_requests_action': 'Review in Settings',
        'settings.group_back': 'Back to Groups',
        'settings.group_tab_my': 'My Groups',
        'settings.group_tab_browse': 'Browse',
        'settings.group_search_placeholder': 'Search groups by name or description',
        'settings.group_search_no_results': 'No groups found.',
        'settings.group_join': 'Join',
        'settings.group_requested': 'Requested',
        'settings.group_member': 'Member',
        'settings.group_join_confirm_title': 'Join Group',
        'settings.group_join_confirm_text': 'Join this group?',
        'settings.group_join_request_sent': 'Your request has been sent to the group admin.',
        'settings.group_remove_member_confirm_title': 'Remove Member',
        'settings.group_remove_member_confirm_text': 'Are you sure you want to remove this member?',
        'update.title': 'Update Available',
        'update.message': 'Skillup has been updated. Please restart to use the new version.',
        'update.warning': 'Unsaved work may be lost.',
        'update.restart': 'Restart',
        'update.confirm_title': 'Restart Skillup',
        'update.confirm_text': 'Unsaved work may be lost. Restart now?',
        'help.start_tour': 'Start Tour',
        'help.close': 'Close',
        'help.tip': 'Tips',
        'help.back': 'Back',
        'help.no_help': 'No help available for this app.',
        'help.no_scene': 'No help available for this screen.',
        'help.legend': '←  →  ↑  ↓  Esc'
    },
    ko: {
        'sidebarSubtitle': '데스크탑',
        'menu.home': '바탕화면',
        'menu.settings': '환경설정',
        'menu.back_to_desktop': '바탕화면',
        'menu.exit_app': '앱 종료',
        'menu.running_apps': '실행 중',
        'title.desktop': '바탕화면',
        'title.settings': '환경설정',
        'empty.no_apps': '앱이 없습니다',
        'empty.no_apps_desc': '시작하려면 앱 폴더에 앱을 추가하세요.',
        'settings.general': '일반',
        'settings.language': '언어',
        'settings.theme': '테마',
        'settings.global_hotkey': '전역 단축키',
        'settings.hotkey_desc': '어디서나 Skillup 데스크탑을 실행할 수 있는 전역 단축키를 등록합니다.',
        'settings.hotkey_combination': '단축키 조합',
        'settings.enable_hotkey': '전역 단축키 활성화',
        'settings.hotkey_enabled': '활성화됨',
        'settings.hotkey_disabled': '비활성화됨',
        'settings.desktop_env': '데스크탑 환경:',
        'settings.current_command': '현재 명령:',
        'settings.hotkey_note': '참고: 이 기능은 GNOME 데스크톱 환경에서 작동합니다. KDE/XFCE의 경우 시스템 설정에서 수동으로 단축키를 등록해주세요.',
        'settings.account': '계정',
        'settings.account_photo': '사진',
        'settings.account_change_photo': '변경',
        'settings.account_remove_photo': '제거',
        'settings.account_name': '이름',
        'settings.account_save': '저장',
        'settings.account_id': '아이디',
        'settings.account_name_saved': '저장이 되었습니다.',
        'settings.account_remove_photo_confirm_title': '사진 제거',
        'settings.account_remove_photo_confirm_text': '프로필 사진을 제거하시겠습니까?',
        'settings.about': '정보',
        'settings.build': '빌드',
        'settings.version': '버전',
        'settings.build_date': '빌드일자',
        'settings.suggest': '건의하기',
        'dialog.ok': '확인',
        'dialog.yes': '예',
        'dialog.no': '아니오',
        'dialog.cancel': '취소',
        'app.launch_failed_title': '앱 실행 실패',
        'app.launch_failed_text': '앱을 시작할 수 없습니다.',
        'app.open_new_window_confirm_title': '새창으로 열기',
        'app.open_new_window_confirm_text': '앱이 초기화되어 새창으로 열립니다. 계속하시겠습니까?',
        'settings.groups': '그룹',
        'settings.groups_desc': '사용자 그룹을 만들고 관리합니다.',
        'settings.group_new': '새 그룹',
        'settings.group_name': '그룹 이름',
        'settings.group_name_placeholder': '그룹 이름 입력',
        'settings.group_description': '설명',
        'settings.group_description_placeholder': '짧은 설명 (선택)',
        'settings.group_all_user': '전체 사용자 포함',
        'settings.group_join_policy': '가입 방식',
        'settings.group_join_policy_free': '자유 (누구나 가입 가능)',
        'settings.group_join_policy_approve': '승인 필요',
        'settings.group_join_policy_all_user': '전체 포함',
        'settings.group_create': '생성',
        'settings.group_save': '저장',
        'settings.group_delete': '그룹 삭제',
        'settings.group_delete_confirm_title': '그룹 삭제',
        'settings.group_delete_confirm_text': '이 그룹을 삭제하시겠습니까? 되돌릴 수 없습니다.',
        'settings.group_members': '멤버',
        'settings.group_add_member': '멤버 추가',
        'settings.group_add_member_placeholder': '멤버로 추가할 ID 입력',
        'settings.group_leave': '그룹 탈퇴',
        'settings.group_leave_confirm_title': '그룹 탈퇴',
        'settings.group_leave_confirm_text': '이 그룹에서 탈퇴하시겠습니까?',
        'settings.group_remove_member': '제거',
        'settings.group_grant_admin': '관리자 지정',
        'settings.group_revoke_admin': '관리자 해제',
        'settings.group_admin_badge': '관리자',
        'settings.group_last_admin_error': '마지막 관리자는 제거할 수 없습니다. 먼저 다른 관리자를 지정하세요.',
        'settings.group_join_requests': '가입 요청',
        'settings.group_approve': '승인',
        'settings.group_reject': '거절',
        'settings.group_no_requests': '대기 중인 요청이 없습니다.',
        'settings.group_startup_requests_title': '가입 요청 알림',
        'settings.group_startup_requests_text': '다음 사용자들이 그룹 가입을 요청했습니다:',
        'settings.group_startup_requests_action': '설정에서 검토',
        'settings.group_back': '그룹 목록으로',
        'settings.group_tab_my': '내 그룹',
        'settings.group_tab_browse': '찾아보기',
        'settings.group_search_placeholder': '그룹 이름 또는 설명으로 검색',
        'settings.group_search_no_results': '검색 결과가 없습니다.',
        'settings.group_join': '가입',
        'settings.group_requested': '요청됨',
        'settings.group_member': '멤버',
        'settings.group_join_confirm_title': '그룹 가입',
        'settings.group_join_confirm_text': '이 그룹에 가입하시겠습니까?',
        'settings.group_join_request_sent': '가입 요청이 그룹 관리자에게 전송되었습니다.',
        'settings.group_remove_member_confirm_title': '멤버 제거',
        'settings.group_remove_member_confirm_text': '이 멤버를 제거하시겠습니까?',
        'update.title': '업데이트 감지',
        'update.message': 'Skillup이 업데이트되었습니다. 새로 실행해주세요.',
        'update.warning': '작업 중인 내용이 손상될 수 있습니다.',
        'update.restart': '재시작',
        'update.confirm_title': 'Skillup 재시작',
        'update.confirm_text': '작업 중인 내용이 손상될 수 있습니다. 지금 재시작하시겠습니까?',
        'help.start_tour': '투어 시작',
        'help.close': '닫기',
        'help.tip': '팁',
        'help.back': '뒤로',
        'help.no_help': '이 앱에 대한 도움말이 없습니다.',
        'help.no_scene': '이 화면에 대한 도움말이 없습니다.',
        'help.legend': '←  →  ↑  ↓  Esc'
    }
};

var currentLanguage = 'en';
window.currentLanguage = currentLanguage;
var currentPage = 'home';
var currentApp = null;
var apps = [];
var runningApps = [];
var sidebarCollapsed = false;
